### ISSUE TITLE
support for APE files

### ISSUE THREAD

**Issue by MxMaster3** [MikeWang000000/spek-X#28] opened 2024-05-23 07:49 UTC
Any chance of adding this in a future update.
Thanks for this very handy app!

**Comment by MikeWang000000** [comment] 2024-05-23 15:57
Maybe a duplicate of #26.

APE (Monkey's Audio) files are already supported. Is there any error when reading the file? 🤔

**Comment by MxMaster3** [comment] 2024-05-24 04:14
Hi Mike,

Thanks for the reply.
I noticed the version I was using was an older version, 0.9.0.
The 0.9.3 version has no problem with APE files.

**Comment by MikeWang000000** [comment] 2024-05-24 06:05
Thank you for the feedback. Closing the issue now…

**Closed as completed by MikeWang000000** 2024-05-24 06:05 UTC
